version: "3.7"

services: 
    redis:
        image: redis
        ports:
            - "6379:6379"
    
    db:
        image: postgres
        volumes: 
            - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
        ports: 
            - "5432:5432"
        